---
abstract: 'Module to look up OFAC Sanctioned Countries'
author:
  - 'Daniel Culver'
build_requires:
  Data::Dumper: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Locale::Country: 0
  Module::Build: 0.3601
  Readonly: 0
  Test::Exception: 0
  Test::More: 0
  Test::Most: 0
  YAML: 0.88
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Country-OFAC
requires:
  Carp: 0
  Exporter: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/dculver1986/locale-country-ofac/issues
  homepage: http://search.cpan.org/dist/Locale-Country-OFAC
  repository: git://github.com/dculver1986/locale-country-ofac.git
version: 0.1.0
